callbacks:
  early_stopping:
    min_delta: 0.001
    mode: min
    monitor: val/loss
    patience: 3
  model_checkpoint:
    filename: '{epoch}-{val/loss:.2f}-{val/cer:.2f}'
    mode: min
    monitor: val/loss
    save_top_k: 1
    save_weights_only: true
data:
  batch_size: 8
  num_workers: 0
  pin_memory: false
lit_model:
  d_model: 128
  dim_feedforward: 256
  dropout: 0.3
  gamma: 0.5
  lr: 0.001
  max_output_len: 150
  milestones:
  - 10
  nhead: 4
  num_decoder_layers: 3
  weight_decay: 0.0001
logger:
  project: image-to-latex
seed: 1234
trainer:
  auto_lr_find: false
  check_val_every_n_epoch: 2
  checkpoint_callback: true
  fast_dev_run: false
  gpus: 1
  max_epochs: 15
  min_epochs: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
